### ISSUE TITLE
数据储存问题

### ISSUE THREAD

**Issue by kexue-z** [KafCoppelia/nonebot_plugin_what2eat#3]
- 而不是 `resource` ~~因为里面我存着有色图~~
---
另外，插件第一次的时候并没有正常的创建 `data.json` 与 `greating.json`
此时我的配置是(用的yaml)

```yaml
what2eat_path: data/what2eat
use_preset_menu: true
use_preset_greating: true
```
插件会报错，`FileNotFoundError: [Errno 2] No such file or directory: 'data/what2eat/data.json'`
